WebMVC/Controllers/VideoController.cs
using BLayer.Service;
using DAL.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Drawing.Printing;

namespace WebMVC.Controllers
{
    public class VideoController : Controller
    {
        // GET: VideoController
        private ServiceVideo _serviceVideo;
        private ServiceGenre _serviceGenre;
        private ServiceImage _serviceImage;

        public VideoController(ServiceVideo serviceVideo, ServiceGenre serviceGenre, ServiceImage serviceImage)
        {
            _serviceVideo = serviceVideo;
            _serviceGenre = serviceGenre;
            _serviceImage = serviceImage;
        }

        public ActionResult Index(string searchString, int genreId, string username, int page = 1, int pageSize = 5)
        {

            var allVideos = _serviceVideo.GetAll();

            if (!string.IsNullOrEmpty(searchString))
            {
                allVideos = allVideos.Where(video => video.Name.Contains(searchString, StringComparison.OrdinalIgnoreCase));
            }
            if (genreId != 0)
            {
                allVideos = allVideos.Where(video => video.GenreId == genreId);
            }

            var videosWithDetails = allVideos.Select(video =>
            {
                var genre = _serviceGenre.GetById(video.GenreId);
                video.Genre = genre;
                return video;
            });
            var paginatedVideos = PaginatedList<Video>.Create(videosWithDetails, page, pageSize);

            var allGenres = _serviceGenre.GetAll();

            ViewBag.Genres = allGenres;
            return View(paginatedVideos);
        }

        // GET: VideoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: VideoController/Create
        public ActionResult Create()
        {
            var dbImages = _serviceImage.GetAll();
            var dbGenres = _serviceGenre.GetAll();
            ViewBag.GenreId = new SelectList(dbGenres, "Id", "Name");
            ViewBag.ImageId = new SelectList(dbImages, "Id", "Content");
            return View();
        }

        // POST: VideoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Video video)
        {
            try
            {
                int selectedGenreId = video.GenreId;
                _serviceVideo.Add(video);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VideoController/Edit/5
        public ActionResult Edit(int id)
        {
            var dbImages = _serviceImage.GetAll();
            var dbGenres = _serviceGenre.GetAll();
            ViewBag.GenreId = new SelectList(dbGenres, "Id", "Name");
            ViewBag.ImageId = new SelectList(dbImages , "Id", "Content");
            return View(_serviceVideo.GetById(id));
        }

        // POST: VideoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Video video)
        {
            try
            {
                var foundVideo = _serviceVideo.GetById(id);
                if (foundVideo != null)
                {
                    foundVideo.Id = video.Id;
                    foundVideo.Name = video.Name;
                    foundVideo.Description = video.Description;
                    foundVideo.GenreId = video.GenreId;
                    foundVideo.Genre = video.Genre;
                    foundVideo.TotalSeconds = video.TotalSeconds;
                    foundVideo.StreamingUrl = video.StreamingUrl;
                    foundVideo.Image = video.Image;
                    foundVideo.ImageId = video.ImageId;
                    foundVideo.CreatedAt = video.CreatedAt;
                    _serviceVideo.Update(foundVideo);
                }
                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return View();
            }
        }

        // GET: VideoController/Delete/5
        public ActionResult Delete(int id)
        {
            var video = _serviceVideo.GetById(id);
            var genreName = _serviceGenre.GetById(video.GenreId).Name;
            ViewBag.Genre = genreName;
            return View(video);
        }

        // POST: VideoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Video video)
        {
            try
            {
                _serviceVideo.DeleteById(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebMVC/Views/Video/Create.cshtml
@model DAL.Models.Video

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Video</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId">
                    <option value="">Select a Genre</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ImageId" class="control-label"></label>
                <select asp-for="ImageId" class="form-control" asp-items="ViewBag.ImageId"></select>
                <span asp-validation-for="ImageId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalSeconds" class="control-label"></label>
                <input asp-for="TotalSeconds" class="form-control" />
                <span asp-validation-for="TotalSeconds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreamingUrl" class="control-label"></label>
                <input asp-for="StreamingUrl" class="form-control" />
                <span asp-validation-for="StreamingUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebMVC/Views/Video/Delete.cshtml
@model DAL.Models.Video

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Video</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalSeconds)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalSeconds)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StreamingUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StreamingUrl)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Genre")
        </dt>
        <dd class="col-sm-10">
            @ViewBag.Genre
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebMVC/Views/Video/Edit.cshtml
@model DAL.Models.Video

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Video</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId"></select>
                <span asp-validation-for="GenreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalSeconds" class="control-label"></label>
                <input asp-for="TotalSeconds" class="form-control" />
                <span asp-validation-for="TotalSeconds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreamingUrl" class="control-label"></label>
                <input asp-for="StreamingUrl" class="form-control" />
                <span asp-validation-for="StreamingUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageId" class="control-label"></label>
                <select asp-for="ImageId" class="form-control" asp-items="ViewBag.ImageId"></select>
                <span asp-validation-for="ImageId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebMVC/Views/Video/Index.cshtml
@model PaginatedList<DAL.Models.Video>

@{
    ViewData["Title"] = "Index";
}

<div class="container mt-4">
    <h1>Videos</h1>

    <p>
        <a class="btn btn-primary" asp-action="Create">Create New</a>
    </p>
    <nav class="navbar navbar-light bg-light">
        <div class="d-flex">
            <form class="form-inline" asp-controller="Video" asp-action="Index" method="get">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="searchString">
                <select class="form-control mr-sm-2" name="genreId">
                    <option value="">All Genres</option>
                    @foreach (var genre in ViewBag.Genres)
                    {
                        <option value="@genre.Id">@genre.Name</option>
                    }
                </select>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>           
            </form>
        </div>
    </nav>

    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr style="background-color: #007BFF; color: white;">
                <th>Name</th>
                <th>Description</th>
                <th>Genre</th>
                <th>URL</th>
                <th>Image</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var video in Model)
            {
                <tr>
                    <td>@video.Name</td>
                    <td>@video.Description</td>
                    <td>@video.Genre.Name</td>
                    <td>@video.StreamingUrl</td>
                    <td>@video.ImageId</td>
                    <td>
                        <a class="btn btn-warning" asp-action="Edit" asp-route-id="@video.Id">Edit</a>
                    </td>
                    <td>
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@video.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div>
        Page @(Model.PageIndex) of @Model.TotalPages

        @if (Model.HasPreviousPage)
        {
            <a href="@Url.Action("Index", new { page = Model.PageIndex - 1, pageSize = Model.PageSize })">Previous</a>
        }
        else
        {
            <span>Previous</span>
        }

        @if (Model.HasNextPage)
        {
            <a href="@Url.Action("Index", new { page = Model.PageIndex + 1, pageSize = Model.PageSize })">Next</a>
        }
        else
        {
            <span>Next</span>
        }
    </div>
</div>